FROM node:alpine

EXPOSE 8000

RUN apk update && apk --no-cache add --virtual builds-deps build-base python3 py3-pip

# Add docker-compose-wait tool
ENV WAIT_VERSION 2.7.2
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/$WAIT_VERSION/wait /wait
RUN chmod +x /wait

WORKDIR /app
COPY ./package.json ./
COPY yarn.lock ./
RUN yarn install --frozen-lockfile

COPY . .
RUN yarn run seed
CMD ["yarn", "start"]
